package com.khy.demosaga.model;

public enum SagaEvents {
    ORDER_REQUEST,
    DISCOUNT_CHECK,
    POINT_CHECK,
    DISCOUNT_REQUEST,
    PAYMENT_REQUEST,
    PAYMENT_CANCEL,
    DISCOUNT_CANCEL,
    ORDER_CANCEL_REQUEST,
    ORDER_CANCEL_FAIL,
    ORDER_CANCEL,
    ORDER_COMPLETE
}
