package com.khy.demosaga.model;

public enum SagaStates {
    ORDER_REQUEST,
    DISCOUNT_CHECK,
    DISCOUNT_CHECK_OK,
    DISCOUNT_CHECK_FAIL,
    POINT_CHECK,
    POINT_CHECK_OK,
    POINT_CHECK_FAIL,
    DISCOUNT_REQUEST,
    DISCOUNT_REQUEST_OK,
    DISCOUNT_REQUEST_FAIL,
    PAYMENT_REQUEST,
    PAYMENT_REQUEST_OK,
    PAYMENT_REQUEST_FAIL,
    PAYMENT_CANCEL,
    PAYMENT_CANCEL_OK,
    PAYMENT_CANCEL_FAIL,
    DISCOUNT_CANCEL,
    DISCOUNT_CANCEL_OK,
    DISCOUNT_CANCEL_FAIL,
    ORDER_CANCEL_REQUEST,
    ORDER_CANCEL_FAIL,
    ORDER_CANCEL,
    ORDER_COMPLETE
}
