package com.khy.demosaga.model;

public enum SagaStates {
    ORDER_REQUEST,
    DISCOUNT_CHECKED,
    DISCOUNT_CHECK_OK,
    DISCOUNT_CHECK_FAIL,
    POINT_CHECKED,
    POINT_CHECK_OK,
    POINT_CHECK_FAIL,
    DISCOUNT_REQUESTED,
    DISCOUNT_REQUEST_OK,
    DISCOUNT_REQUEST_FAIL,
    PAYMENT_REQUESTED,
    PAYMENT_REQUEST_OK,
    PAYMENT_REQUEST_FAIL,
    PAYMENT_CANCELED,
    PAYMENT_CANCEL_OK,
    PAYMENT_CANCEL_FAIL,
    DISCOUNT_CANCELED,
    DISCOUNT_CANCEL_OK,
    DISCOUNT_CANCEL_FAIL,
    ORDER_CANCEL_FAIL,
    ORDER_CANCELED,
    ORDER_COMPLETED
}
