### Get
GET http://localhost:9090/v1/point/check/ok

### Send Post request
POST http://localhost:9090/v1/nextPost
Content-Type: application/json

{
  "customerId": 3003,
  "orderId": 30001,
  "productId": 10,
  "amount": 3300,
  "shippingAddress": "seoul jongro-gu",
  "currentState": "ORDER_REQUEST"
}

### Send Post request
POST http://localhost:9090/v1/nextPost
Content-Type: application/json

{
  "customerId": 3003,
  "orderId": 30001,
  "productId": 10,
  "amount": 3300,
  "shippingAddress": "seoul jongro-gu",
  "currentState": "ORDER_CANCEL_REQUEST"
}




### Send Post request
POST http://localhost:9090/v1/nextPost
Content-Type: application/json

{
  "customerId": 3,
  "orderId": 3,
  "productId": 10,
  "amount": 3300,
  "shippingAddress": "seoul jongro-gu",
  "currentState": "DISCOUNT_CHECK_OK",
  "value": ""
}



### Send Post request
POST http://localhost:9090/v1/nextPost
Content-Type: application/json

{
  "customerId": 3,
  "orderId": 3,
  "productId": 10,
  "amount": 3300,
  "shippingAddress": "seoul jongro-gu",
  "currentState": "DISCOUNT_CHECK_FAIL",
  "value": ""
}

### Send Post request
POST http://localhost:9090/v1/nextPost
Content-Type: application/json

{
  "customerId": 3,
  "orderId": 3,
  "productId": 10,
  "amount": 3300,
  "shippingAddress": "seoul jongro-gu",
  "currentState": "DISCOUNT_REQUEST_OK",
  "value": ""
}

### Send Post request
POST http://localhost:9090/v1/nextPost
Content-Type: application/json

{
  "customerId": 3,
  "orderId": 3,
  "productId": 10,
  "amount": 3300,
  "shippingAddress": "seoul jongro-gu",
  "currentState": "DISCOUNT_REQUEST_FAIL",
  "value": ""
}

### Send Post request
POST http://localhost:9090/v1/nextPost
Content-Type: application/json

{
  "customerId": 3,
  "orderId": 3,
  "productId": 10,
  "amount": 3300,
  "shippingAddress": "seoul jongro-gu",
  "currentState": "PAYMENT_REQUEST_OK",
  "value": ""
}



### Send Post request
POST http://localhost:9090/v1/nextPost
Content-Type: application/json

{
  "customerId": 3,
  "orderId": 3,
  "productId": 10,
  "amount": 3300,
  "shippingAddress": "seoul jongro-gu",
  "currentState": "PAYMENT_REQUEST_FAIL",
  "value": ""
}

### Send Post request
POST http://localhost:9090/v1/nextPost
Content-Type: application/json

{
  "customerId": 3,
  "orderId": 3,
  "productId": 10,
  "amount": 3300,
  "shippingAddress": "seoul jongro-gu",
  "currentState": "PAYMENT_CANCEL_OK",
  "value": ""
}


### Send Post request
POST http://localhost:9090/v1/nextPost
Content-Type: application/json

{
  "customerId": 3,
  "orderId": 3,
  "productId": 10,
  "amount": 3300,
  "shippingAddress": "seoul jongro-gu",
  "currentState": "PAYMENT_CANCEL_FAIL",
  "value": ""
}

### Send Post request
POST http://localhost:9090/v1/nextPost
Content-Type: application/json

{
  "customerId": 3,
  "orderId": 3,
  "productId": 10,
  "amount": 3300,
  "shippingAddress": "seoul jongro-gu",
  "currentState": "DISCOUNT_CANCEL_OK",
  "value": ""
}



### Send Post request
POST http://localhost:9090/v1/nextPost
Content-Type: application/json

{
  "customerId": 3,
  "orderId": 3,
  "productId": 10,
  "amount": 3300,
  "shippingAddress": "seoul jongro-gu",
  "currentState": "DISCOUNT_CANCEL_FAIL",
  "value": ""
}



### Send Post request
POST http://localhost:9090/v1/nextPost
Content-Type: application/json

{
  "customerId": 3,
  "orderId": 3,
  "productId": 10,
  "amount": 3300,
  "shippingAddress": "seoul jongro-gu",
  "currentState": "ORDER_CANCEL_FAIL",
  "value": ""
}